spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #    username: ENC(GS8mJAMXSRsDohHLeGjHmsF74NyGpty2)
    #    password: ENC(KysJc+nUXqiaZVaejuJJpvsckkrNKPqL)
    #    jdbc-url: ENC(OeSJv8Nr2YS9m/w1hulOVDOe96NtZ/uA8bdh2eTbsEmrmAqkVKcSBytYV23OAK08IobWl2wpsXQnmoef5bUecfFipvWGm1TJ66C4J8uRCmbgYiSaOvdwBA==)
    #    url: ENC(tVnzqapg3VeEvSspQtfccGkvYrMpgIEEErReQxx0veBIqwakoZt/tl2zre7yUxgQHQAk0bZ05Ik5nec1NyhWk8vGYa5J5uQKmk2T90iTEpdLX2DVduf3mw==)
    username: root
    password: seung123
    url: jdbc:mysql://localhost:3306/devdb?allowMultiQueries=true # 새로운 db서버
#    url: jdbc:log4jdbc:mariadb://121.170.188.98:33316/terarosa?allowMultiQueries=true # 새로운 db서버
  freemarker:
    cache: false
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  web:
    resources:
      static-locations: classpath:/static/
      add-mappings: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

server.port: 14402

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    multiple-result-sets-enabled: false
  #    jdbc-type-for-null: varchar
  mapper-locations: classpath:mybatis/mapper/**/*.xml
  type-aliases-package: com.api.spring_api.vo, com.api.spring_api.dto


